
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Oct 23 22:41:47 CST 2018
//----------------------------------------------------

package ASM.Analizador;

import ASM.Arbol.*;
import java_cup.runtime.*;
import java.io.*;
import java.lang.*;
import java.util.*;
import java.util.ArrayList;

/** CUP v0.10k generated parser.
  * @version Tue Oct 23 22:41:47 CST 2018
  */
public class ParserASM extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ParserASM() {super();}

  /** Constructor which sets the default scanner. */
  public ParserASM(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\030\000\002\002\004\000\002\003\003\000\002\005" +
    "\003\000\002\005\004\000\002\004\007\000\002\004\006" +
    "\000\002\006\003\000\002\006\004\000\002\010\003\000" +
    "\002\010\003\000\002\010\003\000\002\010\003\000\002" +
    "\010\003\000\002\010\003\000\002\010\003\000\002\010" +
    "\004\000\002\010\004\000\002\010\004\000\002\010\004" +
    "\000\002\007\003\000\002\007\003\000\002\007\004\000" +
    "\002\007\004\000\002\007\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\044\000\004\023\004\001\002\000\004\024\012\001" +
    "\002\000\006\002\uffff\023\uffff\001\002\000\006\002\000" +
    "\023\004\001\002\000\004\002\010\001\002\000\004\002" +
    "\001\001\002\000\006\002\ufffe\023\ufffe\001\002\000\004" +
    "\027\013\001\002\000\040\015\026\016\024\017\021\020" +
    "\025\021\034\022\014\024\027\025\032\026\031\030\015" +
    "\032\035\033\017\034\030\035\016\036\023\001\002\000" +
    "\040\015\ufff3\016\ufff3\017\ufff3\020\ufff3\021\ufff3\022\ufff3" +
    "\024\ufff3\025\ufff3\026\ufff3\030\ufff3\032\ufff3\033\ufff3\034" +
    "\ufff3\035\ufff3\036\ufff3\001\002\000\006\002\ufffc\023\ufffc" +
    "\001\002\000\012\024\027\025\032\026\031\036\023\001" +
    "\002\000\012\024\027\025\032\026\031\036\023\001\002" +
    "\000\040\015\ufffb\016\ufffb\017\ufffb\020\ufffb\021\ufffb\022" +
    "\ufffb\024\ufffb\025\ufffb\026\ufffb\030\ufffb\032\ufffb\033\ufffb" +
    "\034\ufffb\035\ufffb\036\ufffb\001\002\000\040\015\ufff6\016" +
    "\ufff6\017\ufff6\020\ufff6\021\ufff6\022\ufff6\024\ufff6\025\ufff6" +
    "\026\ufff6\030\ufff6\032\ufff6\033\ufff6\034\ufff6\035\ufff6\036" +
    "\ufff6\001\002\000\040\015\026\016\024\017\021\020\025" +
    "\021\034\022\014\024\027\025\032\026\031\030\043\032" +
    "\035\033\017\034\030\035\016\036\023\001\002\000\006" +
    "\025\041\026\042\001\002\000\040\015\ufff7\016\ufff7\017" +
    "\ufff7\020\ufff7\021\ufff7\022\ufff7\024\ufff7\025\ufff7\026\ufff7" +
    "\030\ufff7\032\ufff7\033\ufff7\034\ufff7\035\ufff7\036\ufff7\001" +
    "\002\000\040\015\ufff5\016\ufff5\017\ufff5\020\ufff5\021\ufff5" +
    "\022\ufff5\024\ufff5\025\ufff5\026\ufff5\030\ufff5\032\ufff5\033" +
    "\ufff5\034\ufff5\035\ufff5\036\ufff5\001\002\000\040\015\ufff8" +
    "\016\ufff8\017\ufff8\020\ufff8\021\ufff8\022\ufff8\024\ufff8\025" +
    "\ufff8\026\ufff8\030\ufff8\032\ufff8\033\ufff8\034\ufff8\035\ufff8" +
    "\036\ufff8\001\002\000\004\031\040\001\002\000\012\024" +
    "\027\025\032\026\031\036\023\001\002\000\040\015\uffee" +
    "\016\uffee\017\uffee\020\uffee\021\uffee\022\uffee\024\uffee\025" +
    "\uffee\026\uffee\030\uffee\032\uffee\033\uffee\034\uffee\035\uffee" +
    "\036\uffee\001\002\000\040\015\uffed\016\uffed\017\uffed\020" +
    "\uffed\021\uffed\022\uffed\024\uffed\025\uffed\026\uffed\030\uffed" +
    "\032\uffed\033\uffed\034\uffed\035\uffed\036\uffed\001\002\000" +
    "\040\015\ufff9\016\ufff9\017\ufff9\020\ufff9\021\ufff9\022\ufff9" +
    "\024\ufff9\025\ufff9\026\ufff9\030\ufff9\032\ufff9\033\ufff9\034" +
    "\ufff9\035\ufff9\036\ufff9\001\002\000\040\015\ufff4\016\ufff4" +
    "\017\ufff4\020\ufff4\021\ufff4\022\ufff4\024\ufff4\025\ufff4\026" +
    "\ufff4\030\ufff4\032\ufff4\033\ufff4\034\ufff4\035\ufff4\036\ufff4" +
    "\001\002\000\012\024\027\025\032\026\031\036\023\001" +
    "\002\000\040\015\ufff1\016\ufff1\017\ufff1\020\ufff1\021\ufff1" +
    "\022\ufff1\024\ufff1\025\ufff1\026\ufff1\030\ufff1\032\ufff1\033" +
    "\ufff1\034\ufff1\035\ufff1\036\ufff1\001\002\000\040\015\ufff2" +
    "\016\ufff2\017\ufff2\020\ufff2\021\ufff2\022\ufff2\024\ufff2\025" +
    "\ufff2\026\ufff2\030\ufff2\032\ufff2\033\ufff2\034\ufff2\035\ufff2" +
    "\036\ufff2\001\002\000\040\015\uffec\016\uffec\017\uffec\020" +
    "\uffec\021\uffec\022\uffec\024\uffec\025\uffec\026\uffec\030\uffec" +
    "\032\uffec\033\uffec\034\uffec\035\uffec\036\uffec\001\002\000" +
    "\040\015\uffea\016\uffea\017\uffea\020\uffea\021\uffea\022\uffea" +
    "\024\uffea\025\uffea\026\uffea\030\uffea\032\uffea\033\uffea\034" +
    "\uffea\035\uffea\036\uffea\001\002\000\040\015\uffeb\016\uffeb" +
    "\017\uffeb\020\uffeb\021\uffeb\022\uffeb\024\uffeb\025\uffeb\026" +
    "\uffeb\030\uffeb\032\uffeb\033\uffeb\034\uffeb\035\uffeb\036\uffeb" +
    "\001\002\000\006\002\ufffd\023\ufffd\001\002\000\040\015" +
    "\ufffa\016\ufffa\017\ufffa\020\ufffa\021\ufffa\022\ufffa\024\ufffa" +
    "\025\ufffa\026\ufffa\030\ufffa\032\ufffa\033\ufffa\034\ufffa\035" +
    "\ufffa\036\ufffa\001\002\000\040\015\uffef\016\uffef\017\uffef" +
    "\020\uffef\021\uffef\022\uffef\024\uffef\025\uffef\026\uffef\030" +
    "\uffef\032\uffef\033\uffef\034\uffef\035\uffef\036\uffef\001\002" +
    "\000\040\015\ufff0\016\ufff0\017\ufff0\020\ufff0\021\ufff0\022" +
    "\ufff0\024\ufff0\025\ufff0\026\ufff0\030\ufff0\032\ufff0\033\ufff0" +
    "\034\ufff0\035\ufff0\036\ufff0\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\044\000\010\003\006\004\004\005\005\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\004\010\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\006\021\007\032\010\017\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\007\045\001" +
    "\001\000\004\007\044\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\007\032\010\043\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\007\036\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\007\035\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserASM$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserASM$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserASM$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



 /* -------------------------==: DECLARAR EL ARBOL :==--------------------------*/
    //public Nodo Gramaticas;     
    public static String cadena;
	public static ListaFunciones funcionesArchivo;

	

	

/* -------------------------==: ERROR SINTACTICO :==--------------------------*/
public void syntax_error(Symbol s){
    System.out.println("Error Sintactico -> lexema: " +s.value+" Linea: " +s.right+ " Columna: "+s.left);
    cadena += "<tr>"
                + "<td><center><b>" + s.value + "</b></center></td>"
                + "<td><center><b>" + s.right + "</b></center></td>"
                + "<td><center><b>" + s.left+ "</b></center></td>"
                + "</tr>";
				
}

/* ------------------==: ERROR SINTACTICO NO RECUPERABLE :==------------------*/
public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
    System.out.println("Error Sintactico No Recuperable-> Lexema: " +s.value+" Linea: "+s.right+ " Columna: "+s.left);
     cadena += "<tr>"
                + "<td><center><b>" + s.value + "</b></center></td>"
                + "<td><center><b>" + s.right + "</b></center></td>"
                + "<td><center><b>" + s.left+ "</b></center></td>"
                + "</tr>";
				
}


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ParserASM$actions {


//Operaciones_Listas operaciones = new Operaciones_Listas();



  private final ParserASM parser;

  /** Constructor */
  CUP$ParserASM$actions(ParserASM parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$ParserASM$do_action(
    int                        CUP$ParserASM$act_num,
    java_cup.runtime.lr_parser CUP$ParserASM$parser,
    java.util.Stack            CUP$ParserASM$stack,
    int                        CUP$ParserASM$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserASM$result;

      /* select the action based on the action number */
      switch (CUP$ParserASM$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // VALOR ::= menos numero_entero 
            {
              Object RESULT = null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).value;
		RESULT = new Decimal("-"+a);
              CUP$ParserASM$result = new java_cup.runtime.Symbol(5/*VALOR*/, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-1)).left, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right, RESULT);
            }
          return CUP$ParserASM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // VALOR ::= menos numero_decimal 
            {
              Object RESULT = null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).value;
		RESULT = new Decimal("-"+a);
              CUP$ParserASM$result = new java_cup.runtime.Symbol(5/*VALOR*/, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-1)).left, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right, RESULT);
            }
          return CUP$ParserASM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // VALOR ::= dolar calc 
            {
              Object RESULT = null;
		RESULT= new Calc();
              CUP$ParserASM$result = new java_cup.runtime.Symbol(5/*VALOR*/, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-1)).left, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right, RESULT);
            }
          return CUP$ParserASM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // VALOR ::= numero_entero 
            {
              Object RESULT = null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).value;
		RESULT = new Entero(a);
              CUP$ParserASM$result = new java_cup.runtime.Symbol(5/*VALOR*/, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).left, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right, RESULT);
            }
          return CUP$ParserASM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // VALOR ::= numero_decimal 
            {
              Object RESULT = null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).value;
		RESULT = new Decimal(a);
              CUP$ParserASM$result = new java_cup.runtime.Symbol(5/*VALOR*/, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).left, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right, RESULT);
            }
          return CUP$ParserASM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // SENTENCIA ::= get_local VALOR 
            {
              Object RESULT = null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).value;
		RESULT= new Get_local(a);
              CUP$ParserASM$result = new java_cup.runtime.Symbol(6/*SENTENCIA*/, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-1)).left, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right, RESULT);
            }
          return CUP$ParserASM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // SENTENCIA ::= get_global VALOR 
            {
              Object RESULT = null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).value;
		RESULT= new Get_global(a);
              CUP$ParserASM$result = new java_cup.runtime.Symbol(6/*SENTENCIA*/, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-1)).left, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right, RESULT);
            }
          return CUP$ParserASM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // SENTENCIA ::= set_local VALOR 
            {
              Object RESULT = null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).value;
		RESULT= new Set_local(a);
              CUP$ParserASM$result = new java_cup.runtime.Symbol(6/*SENTENCIA*/, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-1)).left, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right, RESULT);
            }
          return CUP$ParserASM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // SENTENCIA ::= set_global VALOR 
            {
              Object RESULT = null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).value;
		RESULT= new Set_global(a);
              CUP$ParserASM$result = new java_cup.runtime.Symbol(6/*SENTENCIA*/, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-1)).left, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right, RESULT);
            }
          return CUP$ParserASM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // SENTENCIA ::= print 
            {
              Object RESULT = null;
		RESULT= new PRINT();
              CUP$ParserASM$result = new java_cup.runtime.Symbol(6/*SENTENCIA*/, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).left, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right, RESULT);
            }
          return CUP$ParserASM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // SENTENCIA ::= mod 
            {
              Object RESULT = null;
		RESULT= new MOD();
              CUP$ParserASM$result = new java_cup.runtime.Symbol(6/*SENTENCIA*/, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).left, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right, RESULT);
            }
          return CUP$ParserASM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // SENTENCIA ::= div 
            {
              Object RESULT = null;
		RESULT= new DIV();
              CUP$ParserASM$result = new java_cup.runtime.Symbol(6/*SENTENCIA*/, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).left, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right, RESULT);
            }
          return CUP$ParserASM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // SENTENCIA ::= mult 
            {
              Object RESULT = null;
		RESULT= new MULT();
              CUP$ParserASM$result = new java_cup.runtime.Symbol(6/*SENTENCIA*/, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).left, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right, RESULT);
            }
          return CUP$ParserASM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // SENTENCIA ::= diff 
            {
              Object RESULT = null;
		RESULT= new DIFF();
              CUP$ParserASM$result = new java_cup.runtime.Symbol(6/*SENTENCIA*/, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).left, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right, RESULT);
            }
          return CUP$ParserASM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // SENTENCIA ::= add 
            {
              Object RESULT = null;
		RESULT= new ADD();
              CUP$ParserASM$result = new java_cup.runtime.Symbol(6/*SENTENCIA*/, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).left, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right, RESULT);
            }
          return CUP$ParserASM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // SENTENCIA ::= VALOR 
            {
              Object RESULT = null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).value;
		RESULT= a;
              CUP$ParserASM$result = new java_cup.runtime.Symbol(6/*SENTENCIA*/, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).left, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right, RESULT);
            }
          return CUP$ParserASM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // LISTA_VALORES ::= LISTA_VALORES SENTENCIA 
            {
              Object RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-1)).right;
		Object l = (Object)((java_cup.runtime.Symbol) CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-1)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).value;
		
			CuerpoFuncion c = (CuerpoFuncion)l;
			c.insertar(a);
			RESULT= c;
		
              CUP$ParserASM$result = new java_cup.runtime.Symbol(4/*LISTA_VALORES*/, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-1)).left, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right, RESULT);
            }
          return CUP$ParserASM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // LISTA_VALORES ::= SENTENCIA 
            {
              Object RESULT = null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).value;
		
			CuerpoFuncion c = new CuerpoFuncion();
			c.insertar(a);
			RESULT= c;
		
              CUP$ParserASM$result = new java_cup.runtime.Symbol(4/*LISTA_VALORES*/, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).left, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right, RESULT);
            }
          return CUP$ParserASM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // FUNCION ::= function dolar identificador end 
            {
              Object RESULT = null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-1)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-1)).value;
		RESULT= new Funcion(a, new CuerpoFuncion());
              CUP$ParserASM$result = new java_cup.runtime.Symbol(2/*FUNCION*/, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-3)).left, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right, RESULT);
            }
          return CUP$ParserASM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // FUNCION ::= function dolar identificador LISTA_VALORES end 
            {
              Object RESULT = null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-1)).right;
		Object b = (Object)((java_cup.runtime.Symbol) CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-1)).value;
		RESULT = new Funcion(a, b);
              CUP$ParserASM$result = new java_cup.runtime.Symbol(2/*FUNCION*/, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-4)).left, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right, RESULT);
            }
          return CUP$ParserASM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // LISTA_FUNCIONES ::= LISTA_FUNCIONES FUNCION 
            {
              Object RESULT = null;
		int lleft = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-1)).right;
		Object l = (Object)((java_cup.runtime.Symbol) CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-1)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).value;
		
			ListaFunciones c = (ListaFunciones)l;
			c.insertar(a);
			RESULT= c;
		
              CUP$ParserASM$result = new java_cup.runtime.Symbol(3/*LISTA_FUNCIONES*/, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-1)).left, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right, RESULT);
            }
          return CUP$ParserASM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // LISTA_FUNCIONES ::= FUNCION 
            {
              Object RESULT = null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).value;
		
			ListaFunciones c = new ListaFunciones();
			c.insertar(a);
			RESULT= c;
		
              CUP$ParserASM$result = new java_cup.runtime.Symbol(3/*LISTA_FUNCIONES*/, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).left, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right, RESULT);
            }
          return CUP$ParserASM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= LISTA_FUNCIONES 
            {
              Object RESULT = null;
		int aleft = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).value;
		parser.funcionesArchivo= (ListaFunciones)a;
              CUP$ParserASM$result = new java_cup.runtime.Symbol(1/*INICIO*/, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).left, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right, RESULT);
            }
          return CUP$ParserASM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-1)).value;
		RESULT = start_val;
              CUP$ParserASM$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-1)).left, ((java_cup.runtime.Symbol)CUP$ParserASM$stack.elementAt(CUP$ParserASM$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$ParserASM$parser.done_parsing();
          return CUP$ParserASM$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

