
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Oct 22 22:41:09 CST 2018
//----------------------------------------------------

package ASM.Analizador;

/** CUP generated class containing symbol constants. */
public class simbolosASM {
  /* terminals */
  public static final int cierraPar = 5;
  public static final int print = 16;
  public static final int end = 22;
  public static final int coma = 9;
  public static final int abreLlave = 2;
  public static final int mult = 13;
  public static final int function = 17;
  public static final int punto = 10;
  public static final int nulo = 8;
  public static final int diff = 12;
  public static final int div = 14;
  public static final int dolar = 18;
  public static final int add = 11;
  public static final int EOF = 0;
  public static final int cierraLlave = 3;
  public static final int numero_decimal = 20;
  public static final int error = 1;
  public static final int numero_entero = 19;
  public static final int dosPuntos = 6;
  public static final int puntoComa = 7;
  public static final int abrePar = 4;
  public static final int mod = 15;
  public static final int identificador = 21;
}

