
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Oct 25 00:43:18 CST 2018
//----------------------------------------------------

package ASM.Analizador;

/** CUP generated class containing symbol constants. */
public class simbolosASM {
  /* terminals */
  public static final int calc = 23;
  public static final int lte = 31;
  public static final int cierraPar = 5;
  public static final int print = 16;
  public static final int end = 22;
  public static final int coma = 9;
  public static final int get_global = 27;
  public static final int get_local = 25;
  public static final int abreLlave = 2;
  public static final int mult = 13;
  public static final int function = 17;
  public static final int lt = 29;
  public static final int gte = 32;
  public static final int menos = 28;
  public static final int punto = 10;
  public static final int nulo = 8;
  public static final int diff = 12;
  public static final int div = 14;
  public static final int br_if = 34;
  public static final int dolar = 18;
  public static final int add = 11;
  public static final int EOF = 0;
  public static final int gt = 30;
  public static final int set_global = 26;
  public static final int cierraLlave = 3;
  public static final int numero_decimal = 20;
  public static final int error = 1;
  public static final int numero_entero = 19;
  public static final int dosPuntos = 6;
  public static final int puntoComa = 7;
  public static final int br = 33;
  public static final int abrePar = 4;
  public static final int mod = 15;
  public static final int set_local = 24;
  public static final int identificador = 21;
}

