
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Oct 21 22:15:38 CST 2018
//----------------------------------------------------

package DracoScript.Analizador;

/** CUP generated class containing symbol constants. */
public class simbolosDraco {
  /* terminals */
  public static final int t_for = 19;
  public static final int t_String = 26;
  public static final int distintoA = 43;
  public static final int cierraLlave = 9;
  public static final int residuo = 37;
  public static final int oval = 24;
  public static final int menosMenos = 31;
  public static final int dosPuntos = 12;
  public static final int masMas = 30;
  public static final int notIf = 15;
  public static final int dasm = 55;
  public static final int abreLlave = 8;
  public static final int nulo = 27;
  public static final int coma = 28;
  public static final int igual = 48;
  public static final int line = 25;
  public static final int identificador = 50;
  public static final int multiplicacion = 34;
  public static final int runMultDasm = 21;
  public static final int t_cadena = 4;
  public static final int caracter = 53;
  public static final int menorIgual = 40;
  public static final int si = 14;
  public static final int t_booleano = 6;
  public static final int smash = 17;
  public static final int numero_decimal = 52;
  public static final int menos = 33;
  public static final int menor = 38;
  public static final int quadrate = 23;
  public static final int var = 7;
  public static final int EOF = 0;
  public static final int mas = 32;
  public static final int mayorIgual = 41;
  public static final int error = 1;
  public static final int mayor = 39;
  public static final int or = 45;
  public static final int punto = 29;
  public static final int elif = 16;
  public static final int point = 22;
  public static final int potencia = 36;
  public static final int valBool = 47;
  public static final int puntoComa = 13;
  public static final int numero_entero = 51;
  public static final int igualIgual = 42;
  public static final int not = 46;
  public static final int and = 44;
  public static final int t_decimal = 3;
  public static final int print = 20;
  public static final int comillaSimple = 54;
  public static final int t_entero = 2;
  public static final int t_caracter = 5;
  public static final int division = 35;
  public static final int abrePar = 10;
  public static final int cadena = 49;
  public static final int t_while = 18;
  public static final int cierraPar = 11;
}

