
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Oct 28 23:24:11 CST 2018
//----------------------------------------------------

package D_Mas_Mas.Analizador;

/** CUP generated class containing symbol constants. */
public class simbolosDMM {
  /* terminals */
  public static final int continuar = 48;
  public static final int distintoA = 37;
  public static final int cierraLlave = 8;
  public static final int imprimir = 20;
  public static final int residuo = 31;
  public static final int menosMenos = 25;
  public static final int dosPuntos = 13;
  public static final int masMas = 24;
  public static final int abreLlave = 7;
  public static final int detener = 19;
  public static final int nulo = 50;
  public static final int coma = 22;
  public static final int igual = 42;
  public static final int identificador = 44;
  public static final int multiplicacion = 28;
  public static final int t_cadena = 4;
  public static final int caracter = 58;
  public static final int menorIgual = 34;
  public static final int si = 15;
  public static final int mientras = 18;
  public static final int t_booleano = 6;
  public static final int ovalo = 56;
  public static final int importar = 49;
  public static final int estructura = 51;
  public static final int numero_decimal = 46;
  public static final int menos = 27;
  public static final int menor = 32;
  public static final int EOF = 0;
  public static final int cuadrado = 55;
  public static final int mas = 26;
  public static final int mayorIgual = 35;
  public static final int para = 17;
  public static final int error = 1;
  public static final int mayor = 33;
  public static final int puntoD = 54;
  public static final int or = 39;
  public static final int punto = 23;
  public static final int vacio = 52;
  public static final int potencia = 30;
  public static final int valBool = 41;
  public static final int puntoComa = 14;
  public static final int numero_entero = 45;
  public static final int igualIgual = 36;
  public static final int not = 40;
  public static final int and = 38;
  public static final int linea = 57;
  public static final int t_decimal = 3;
  public static final int retornar = 21;
  public static final int t_entero = 2;
  public static final int t_caracter = 5;
  public static final int abreCor = 11;
  public static final int principal = 53;
  public static final int cierraCor = 12;
  public static final int division = 29;
  public static final int interrogacion = 47;
  public static final int abrePar = 9;
  public static final int cadena = 43;
  public static final int sino = 16;
  public static final int cierraPar = 10;
}

